import { MatPaginatorIntl } from '@angular/material/paginator';
import { createMaterialPaginatorIntl } from '../../shared/material-paginator-intl';
import { MatPaginatorModule } from '@angular/material/paginator';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { CommonModule } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  inject,
  OnInit,
} from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { Router } from '@angular/router';
import { switchMap } from 'rxjs';
import { NotificationService } from '../../../services/notification.service';
import { ShopNotification } from '../../../models/notification.model';

@Component({
  providers: [
    { provide: MatPaginatorIntl, useFactory: createMaterialPaginatorIntl },
  ],
  selector: 'app-notifications',
  imports: [
    CommonModule,
    MatButtonModule,
    MatCardModule,
    MatProgressBarModule,
    MatPaginatorModule,
  ],
  templateUrl: './notifications.component.html',
  changeDetection: ChangeDetectionStrategy.Eager,
})
export class NotificationsComponent implements OnInit {
  readonly service = inject(NotificationService);
  private readonly router = inject(Router);
  private readonly destroyRef = inject(DestroyRef);
  private revision = 0;
  notifications: ShopNotification[] = [];
  page = 0;
  totalPages = 0;
  totalElements = 0;
  loading = false;
  updating = false;
  error = '';

  ngOnInit(): void {
    this.load();
  }

  load(page = 0): void {
    const revision = ++this.revision;
    this.loading = true;
    this.error = '';
    this.service
      .list(page)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: (result) => {
          if (revision !== this.revision) {
            return;
          }
          this.notifications = result.content;
          this.page = result.number;
          this.totalPages = result.totalPages;
          this.totalElements = result.totalElements;
          this.loading = false;
        },
        error: () => {
          if (revision === this.revision) {
            this.error = 'Không tải được thông báo. Vui lòng thử lại.';
            this.loading = false;
          }
        },
      });
  }

  open(notification: ShopNotification): void {
    if (this.updating) {
      return;
    }
    this.updating = true;
    this.service
      .markRead(notification.id)
      .pipe(
        switchMap(() => this.service.refresh()),
        takeUntilDestroyed(this.destroyRef),
      )
      .subscribe({
        next: (count) => {
          this.updating = false;
          this.service.unread.set(count);
          // Only links generated by our order/review events are navigable.
          if (
            /^\/orders\/\d+$/.test(notification.link) ||
            /^\/products\/\d+(#reviews)?$/.test(notification.link)
          ) {
            void this.router.navigateByUrl(notification.link);
          }
        },
        error: () => {
          this.updating = false;
          this.error = 'Không cập nhật được thông báo.';
        },
      });
  }

  markAll(): void {
    if (this.updating) {
      return;
    }
    this.updating = true;
    this.service
      .markAllRead()
      .pipe(
        switchMap(() => this.service.refresh()),
        takeUntilDestroyed(this.destroyRef),
      )
      .subscribe({
        next: (count) => {
          this.updating = false;
          this.service.unread.set(count);
          this.load(this.page);
        },
        error: () => {
          this.updating = false;
          this.error = 'Không cập nhật được thông báo.';
        },
      });
  }
}
