ALTER TABLE products ADD COLUMN inventory_revision BIGINT NOT NULL DEFAULT 0;
ALTER TABLE product_images ADD COLUMN position INTEGER NOT NULL DEFAULT 0;
CREATE TABLE product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id),
    sku VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    color VARCHAR(60) NOT NULL DEFAULT '',
    size VARCHAR(60) NOT NULL DEFAULT '',
    capacity VARCHAR(60) NOT NULL DEFAULT '',
    price NUMERIC(12,2) NOT NULL CHECK (price >= 0),
    stock INTEGER NOT NULL CHECK (stock >= 0),
    image_url VARCHAR(500),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_variants_id_product UNIQUE(id, product_id)
);
CREATE UNIQUE INDEX uk_variants_product_name ON product_variants(product_id, LOWER(name));
CREATE INDEX idx_variants_product ON product_variants(product_id);
ALTER TABLE order_items ADD COLUMN variant_id BIGINT;
ALTER TABLE order_items ADD COLUMN variant_name VARCHAR(150);
ALTER TABLE order_items ADD COLUMN sku VARCHAR(64);
ALTER TABLE order_items ADD CONSTRAINT fk_order_items_variant_product
    FOREIGN KEY(variant_id, product_id) REFERENCES product_variants(id, product_id);
ALTER TABLE order_items DROP CONSTRAINT uk_order_items_order_product;
CREATE UNIQUE INDEX uk_order_items_legacy ON order_items(order_id, product_id) WHERE variant_id IS NULL;
CREATE UNIQUE INDEX uk_order_items_variant ON order_items(order_id, variant_id) WHERE variant_id IS NOT NULL;
ALTER TABLE order_items ADD CONSTRAINT ck_order_item_variant_snapshot
    CHECK ((variant_id IS NULL AND variant_name IS NULL AND sku IS NULL)
        OR (variant_id IS NOT NULL AND variant_name IS NOT NULL AND sku IS NOT NULL));
