CREATE TABLE vouchers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(40) NOT NULL UNIQUE,
    type VARCHAR(20) NOT NULL CHECK (type IN ('FIXED', 'PERCENT')),
    amount NUMERIC(12,2) NOT NULL CHECK (amount > 0),
    minimum_subtotal NUMERIC(14,2) NOT NULL CHECK (minimum_subtotal >= 0),
    maximum_discount NUMERIC(12,2) NOT NULL CHECK (maximum_discount > 0),
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ NOT NULL CHECK (ends_at > starts_at),
    usage_limit INTEGER NOT NULL CHECK (usage_limit > 0),
    per_user_limit INTEGER NOT NULL CHECK (per_user_limit > 0),
    used_count INTEGER NOT NULL DEFAULT 0 CHECK (used_count >= 0 AND used_count <= usage_limit),
    target_user_id BIGINT REFERENCES users(id),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (type <> 'PERCENT' OR amount <= 100),
    CHECK (code = UPPER(code))
);
ALTER TABLE orders ADD COLUMN shipping_method VARCHAR(20) NOT NULL DEFAULT 'STANDARD'
    CHECK (shipping_method IN ('STANDARD', 'EXPRESS'));
ALTER TABLE orders ADD COLUMN voucher_id BIGINT REFERENCES vouchers(id);
ALTER TABLE orders ADD COLUMN voucher_code VARCHAR(40);
ALTER TABLE orders ADD COLUMN discount NUMERIC(14,2) NOT NULL DEFAULT 0
    CHECK (discount >= 0 AND discount <= subtotal);
ALTER TABLE orders ADD CONSTRAINT ck_order_total CHECK (total = subtotal + shipping_fee - discount);
ALTER TABLE orders ADD CONSTRAINT ck_order_voucher_snapshot
    CHECK ((voucher_id IS NULL AND voucher_code IS NULL AND discount = 0)
        OR (voucher_id IS NOT NULL AND voucher_code IS NOT NULL));
CREATE INDEX idx_orders_voucher_user_status ON orders(voucher_id, user_id, status);
CREATE TABLE order_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    status VARCHAR(30) NOT NULL
        CHECK (status IN ('PENDING','CONFIRMED','SHIPPING','DELIVERED','COMPLETED','CANCELLED')),
    actor VARCHAR(20) NOT NULL CHECK (actor IN ('CUSTOMER','ADMIN','SYSTEM')),
    occurred_at TIMESTAMPTZ NOT NULL,
    imported BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX idx_order_history_order ON order_status_history(order_id, occurred_at, id);
INSERT INTO order_status_history(order_id, status, actor, occurred_at, imported)
SELECT id, status, 'SYSTEM', COALESCE(updated_at, created_at), TRUE FROM orders;
