CREATE TABLE favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_favorites_user_product UNIQUE (user_id, product_id)
);
CREATE INDEX idx_favorites_user_id ON favorites(user_id, id DESC);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    event_key VARCHAR(120) NOT NULL,
    title VARCHAR(160) NOT NULL,
    body VARCHAR(500) NOT NULL,
    link VARCHAR(200) NOT NULL,
    read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_notifications_user_event UNIQUE (user_id, event_key)
);
CREATE INDEX idx_notifications_user_id ON notifications(user_id, id DESC);
CREATE INDEX idx_notifications_unread ON notifications(user_id) WHERE read = FALSE;

-- The notification and the order state commit or roll back together.
-- Existing orders are deliberately not backfilled with invented events.
CREATE FUNCTION notify_order_state() RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
    state_label TEXT;
BEGIN
    IF TG_OP = 'UPDATE' THEN
        IF OLD.status IS NOT DISTINCT FROM NEW.status THEN
            RETURN NEW;
        END IF;
    END IF;
    state_label := CASE NEW.status
        WHEN 'PENDING' THEN 'Đang chờ xác nhận'
        WHEN 'CONFIRMED' THEN 'Đã xác nhận'
        WHEN 'SHIPPING' THEN 'Đang vận chuyển'
        WHEN 'DELIVERED' THEN 'Đã giao, chờ bạn xác nhận nhận hàng'
        WHEN 'COMPLETED' THEN 'Đã hoàn thành, bạn có thể đánh giá sản phẩm'
        WHEN 'CANCELLED' THEN 'Đã hủy'
        ELSE NEW.status
    END;
    INSERT INTO notifications(user_id, event_key, title, body, link)
    VALUES (NEW.user_id, 'order:' || NEW.id || ':' || NEW.status,
        'Cập nhật đơn hàng #' || NEW.id, state_label, '/orders/' || NEW.id)
    ON CONFLICT (user_id, event_key) DO NOTHING;
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_order_notification AFTER INSERT OR UPDATE OF status ON orders
FOR EACH ROW EXECUTE FUNCTION notify_order_state();
