ALTER TABLE products
    ADD COLUMN stock INTEGER NOT NULL DEFAULT 100 CHECK (stock >= 0),
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number UUID NOT NULL UNIQUE,
    user_id BIGINT NOT NULL REFERENCES users(id),
    recipient_name VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    shipping_address VARCHAR(255) NOT NULL,
    note VARCHAR(500) NOT NULL DEFAULT '',
    status VARCHAR(30) NOT NULL CHECK (status IN ('PENDING', 'CONFIRMED', 'SHIPPING', 'DELIVERED', 'CANCELLED')),
    payment_method VARCHAR(20) NOT NULL CHECK (payment_method IN ('COD')),
    subtotal NUMERIC(14, 2) NOT NULL CHECK (subtotal >= 0),
    shipping_fee NUMERIC(14, 2) NOT NULL CHECK (shipping_fee >= 0),
    total NUMERIC(14, 2) NOT NULL CHECK (total >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id),
    product_name VARCHAR(350) NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    line_total NUMERIC(14, 2) NOT NULL CHECK (line_total >= 0),
    CONSTRAINT uk_order_items_order_product UNIQUE (order_id, product_id)
);

CREATE INDEX idx_orders_user_created_at ON orders(user_id, created_at DESC);
CREATE INDEX idx_order_items_order_id ON order_items(order_id);
CREATE INDEX idx_order_items_product_id ON order_items(product_id);
