CREATE TABLE product_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id),
    order_item_id BIGINT NOT NULL REFERENCES order_items(id),
    rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment VARCHAR(1000) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_product_reviews_order_item UNIQUE (order_item_id)
);

CREATE INDEX idx_product_reviews_product_created_at
    ON product_reviews(product_id, created_at DESC);

INSERT INTO product_images(product_id, image_url)
SELECT id, thumbnail FROM products WHERE thumbnail IS NOT NULL AND thumbnail <> '';

INSERT INTO product_images(product_id, image_url)
SELECT product.id,
    CASE product.category_id
        WHEN 1 THEN 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=900&h=900&q=80'
        WHEN 2 THEN 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&h=900&q=80'
        WHEN 3 THEN 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=900&h=900&q=80'
        WHEN 4 THEN 'https://images.unsplash.com/photo-1561154464-82e9adf32764?auto=format&fit=crop&w=900&h=900&q=80'
        WHEN 5 THEN 'https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?auto=format&fit=crop&w=900&h=900&q=80'
        WHEN 6 THEN 'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=900&h=900&q=80'
        WHEN 7 THEN 'https://images.unsplash.com/photo-1585792180666-f7347c490ee2?auto=format&fit=crop&w=900&h=900&q=80'
        WHEN 8 THEN 'https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=900&h=900&q=80'
        WHEN 9 THEN 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=900&h=900&q=80'
        ELSE 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=900&h=900&q=80'
    END
FROM products AS product;

INSERT INTO product_images(product_id, image_url)
SELECT product.id,
    CASE product.category_id
        WHEN 1 THEN 'https://images.unsplash.com/photo-1567581935884-3349723552ca?auto=format&fit=crop&w=900&h=900&q=80'
        WHEN 2 THEN 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?auto=format&fit=crop&w=900&h=900&q=80'
        WHEN 3 THEN 'https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=900&h=900&q=80'
        WHEN 4 THEN 'https://images.unsplash.com/photo-1589739900243-4b52cd9b104e?auto=format&fit=crop&w=900&h=900&q=80'
        WHEN 5 THEN 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=900&h=900&q=80'
        WHEN 6 THEN 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=900&h=900&q=80'
        WHEN 7 THEN 'https://images.unsplash.com/photo-1593640408182-31c70c8268f5?auto=format&fit=crop&w=900&h=900&q=80'
        WHEN 8 THEN 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=900&h=900&q=80'
        WHEN 9 THEN 'https://images.unsplash.com/photo-1563297007-0686b7003af7?auto=format&fit=crop&w=900&h=900&q=80'
        ELSE 'https://images.unsplash.com/photo-1606420187127-8a26fcf0aa5d?auto=format&fit=crop&w=900&h=900&q=80'
    END
FROM products AS product;
