CREATE TABLE user_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    recipient_name VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    shipping_address VARCHAR(255) NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_user_addresses_user ON user_addresses(user_id);
CREATE UNIQUE INDEX uk_user_addresses_default ON user_addresses(user_id) WHERE is_default;

ALTER TABLE orders ADD COLUMN request_id UUID;
ALTER TABLE orders ADD COLUMN request_fingerprint VARCHAR(64);
ALTER TABLE orders ADD CONSTRAINT uk_orders_user_request UNIQUE(user_id, request_id);
ALTER TABLE orders ADD CONSTRAINT ck_orders_request_pair
    CHECK ((request_id IS NULL AND request_fingerprint IS NULL)
        OR (request_id IS NOT NULL AND request_fingerprint IS NOT NULL));
